name: Api Tests
run-name: ${{ github.actor }} is building - testing - deploying

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      
      - name: Build docker container
        run: docker-compose up build

      - name: Testing with PHPUnit
        run: php bin/phpunit tests/ApiTest.php


 