name: Api Tests
run-name: ${{ github.actor }} is building - testing - deploying

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          path: /home/ubuntu/actions-runner/run.sh/api_cesicar/api_cesicar ./
      - uses: isbang/compose-action@v1.5.1
        with:
          compose-file: "./docker-compose.yml"
          compose-flags: build
          services: |
            db
            www
        env:
          DATABASE_URL: "mysql://root:root@db:3306/api_cesicar?serverVersion=mariadb-10.6.7"

      # - name: Testing with PHPUnit
        # run: php bin/phpunit tests/ApiTest.php


 