name: Api Tests
run-name: ${{ github.actor }} is building - testing - deploying

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      # - uses: actions/cache@v3
        # with:
          # path: |
            # /home/runner/.cache/
          # key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      # - name: Set up Docker Buildx
        # uses: docker/setup-buildx-action@v2

      - uses: isbang/compose-action@v1.5.1
        with:
          compose-file: "./docker-compose.yml"
        env:
          DATABASE_URL: "mysql://root:root@db:3306/api_cesicar?serverVersion=mariadb-10.6.7"

      - name: Testing with PHPUnit
        run: php bin/phpunit tests/ApiTest.php


 