name: Api Tests - push recette
run-name: ${{ github.actor }} is updates pre-production app.

on:
  push:
    branches:
      - recette

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Update libraries, migrations
        run: npm install && composer install && php bin/console doctrine:s:u --complete


 